services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: my_inventory
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "ps_isready -U dev_user -d my_inventory"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/my_app_db
      SPRING_DATASOURCE_USERNAME: dev_user
      SPRING_DATASOURCE_PASSWORD: dev_password
    depends_on:
      - db

  admirer:
    image: admirer
    restart: always
    ports:
      - "8081:8080"

volumes:
  postgres_data:

