FROM openjdk:17

COPY target/demo-0.0.1-SNAPSHOT.jar app.jar

# java -jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]


# sample
#FROM ubuntu:latest
#LABEL authors="uttambr"
#
#ENTRYPOINT ["top", "-b"]